# Generated by Django 6.0.3 on 2026-04-12 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='title',
        ),
    ]
