# Generated by Django 6.0.3 on 2026-04-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_remove_ad_description_remove_ad_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='slot',
            field=models.CharField(choices=[('slot_1', 'Slot 1 — Popup ad (shows on app open)'), ('slot_2', 'Slot 2 — Banner ad (shows in home screen)')], default='slot_1', max_length=10),
        ),
    ]
