# Generated by Django 6.0.3 on 2026-04-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_alter_shop_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='category',
            field=models.CharField(choices=[('clothes', 'Clothes'), ('shoes', 'Shoes'), ('both', 'Clothes & Shoes')], default='both', max_length=10),
        ),
    ]
