# Generated by Django 6.0.3 on 2026-04-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_shop_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='category',
            field=models.CharField(choices=[('men_clothes', 'Men Clothes'), ('men_shoes', 'Men Shoes'), ('women_clothes', 'Women Clothes'), ('women_shoes', 'Women Shoes'), ('kids_clothes', 'Kids Clothes'), ('kids_shoes', 'Kids Shoes')], default='men_clothes', max_length=20),
        ),
    ]
