# Generated by Django 6.0.3 on 2026-04-30 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_alter_shop_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['created_at']},
        ),
    ]
